install: ""
php_version: ""
filesystem_version: ""
prod_install: accesslaserstg
stage_install: ""
dev_install: ""
push_environment: ""
pull_environment: ""
last_ssh_event: "2022-01-17T14:37:09-08:00"
last_push_event: "2022-01-17T14:35:17-08:00"
mysql_volume_mount_type: ""
mysql_root_password: ""
mysql_user_password: ""
mysql_user_name: ""
mysql_database_name: ""
xdebug_off_by_default: false
force_ssl: false
wp_debug: false
wp_debug_cli: false
